In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np
# Create a 1-dimensional NumPy array using np.array()
a=np.array([1,2,3,4,5])
# Create a 2-dimensional NumPy array using np.array()
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print(a);print(a.size);print(a.shape);print(a.ndim);print(a.dtype)
print()
# Attributes of 2-dimensional array
print(b);print(b.size);print(b.shape);print(b.ndim);print(b.dtype)



[1 2 3 4 5]
5
(5,)
1
int32

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
(2, 5)
2
int32


In [2]:
# Create an array of shape (5, 5) with only ones
c=np.ones((5,5),dtype='int8')
print(c);print()
# Create an array of shape (3, 3, 5) with only zeros
d=np.zeros((3, 3, 5),dtype='int8')
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [3]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
e=np.random.randint(0,10,14).reshape(7,2)
print(e);print()
# Create a random array of floats between 0 & 1 of shape (3, 5)
f=np.random.random(15).reshape(3,5)
print(f);print()
# Create an array of normally distributed random numbers
g=np.random.rand(5)
print(g)

[[9 3]
 [9 6]
 [8 6]
 [4 6]
 [1 0]
 [8 6]
 [8 6]]

[[0.35974436 0.75909705 0.97722559 0.34775441 0.678775  ]
 [0.95261124 0.102263   0.00673594 0.56754363 0.04615029]
 [0.24799219 0.75341772 0.90957897 0.19334827 0.69665772]]

[0.16343494 0.42821056 0.84131405 0.31606305 0.00217432]


In [4]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
s=np.random.randint(0,10,24).reshape(4,6)
print(s);print()
# Copy the code from the cell above and run it again
t=s.copy()
print(t);print()
# Find the 0'th index of the latest array you created
print(t[0]);print()
# Get the first 2 rows of latest array you created
print(t[0:2]);print()
# Get the first 2 values of the first 2 rows of the latest array
print(t[0:2,0:2])

[[5 0 7 4 7 1]
 [4 7 4 2 1 9]
 [8 6 0 0 9 4]
 [6 7 6 4 8 7]]

[[5 0 7 4 7 1]
 [4 7 4 2 1 9]
 [8 6 0 0 9 4]
 [6 7 6 4 8 7]]

[5 0 7 4 7 1]

[[5 0 7 4 7 1]
 [4 7 4 2 1 9]]

[[5 0]
 [4 7]]


In [5]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
np.random.seed(42)
arr1=np.random.randint(0,10,15).reshape(3,5)
arr2=np.ones((3,5),dtype='int8')
print(arr1);print()
print(arr2);print()
# adding both arrays
arr3=arr1+arr2
print(arr3)

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]]


In [6]:
# Create another array of ones of shape (5, 3)
arr4=np.ones((5,3),dtype='int8')
# Try add the array of ones and the other most recent array together # You can anticipate an error
ab_1=arr4+arr1.reshape(5,3)
print(ab_1);print()
# Do the same operation you just did but this time with a transpose on one array
arr5=arr4+arr3.transpose()
print(arr5);print()
# Take the latest array to the power of 2 using the python way
print(arr5**2);print()
# Do the same thing with numpy way
print(np.square(arr5));print()
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
b1=np.sum(np.square(arr5-arr5.mean()))/arr5.size
print(arr5.mean(),arr5.min(),arr5.max(),arr5.std(),b1)

[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]
 [ 8  3  6]]

[[ 8 11  5]
 [ 5  4  9]
 [ 9  8  9]
 [ 6  9  4]
 [ 8  6  7]]

[[ 64 121  25]
 [ 25  16  81]
 [ 81  64  81]
 [ 36  81  16]
 [ 64  36  49]]

[[ 64 121  25]
 [ 25  16  81]
 [ 81  64  81]
 [ 36  81  16]
 [ 64  36  49]]

7.2 4 11 2.039607805437114 4.16


In [7]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
arr5=np.random.randint(0,10,9).reshape(3,3)
arr6=np.random.randint(0,10,6).reshape(3,2)
print(arr5);print();print(arr6)
print()
# Perform a dot product on the two newest arrays you created
print(np.dot(arr5,arr6))

[[4 1 7]
 [5 1 4]
 [0 9 5]]

[[8 0]
 [9 2]
 [6 3]]

[[ 83  23]
 [ 73  14]
 [111  33]]


In [8]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
arr7=np.random.randint(0,10,12).reshape(4,3)
arr8=np.random.randint(0,10,12).reshape(4,3)
# Perform a hadamard product on the two newest arrays you created
print(np.multiply(arr7,arr8));print()
# Perform a dot product on the two newest arrays you created # Error anticipated
print(np.dot(arr7,arr8.reshape(3,4)));print()
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
print(np.dot(arr7,arr8.transpose()))

[[72 16 36]
 [ 8  6 12]
 [48 42  2]
 [ 0 24  1]]

[[ 82  70  96  50]
 [ 32  34  66  54]
 [ 80  82 111  75]
 [ 37  48  78  69]]

[[124  46  70  10]
 [102  26  62  22]
 [129  41  92  19]
 [100  23  76  25]]


In [9]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
arr9=np.random.randint(0,10,9).reshape(3,3)
arr10=np.random.randint(0,10,9).reshape(3,3)
print(arr9);print()
print(arr10);print()
print(arr10)
# Compare the two arrays with '>', '<=' and '==' 
print(arr9>arr10);print()
print(arr9<=arr10);print()
print(arr9>=arr10);print()
# Sort one of the arrays you just created in ascending order
arr10.sort()
print(arr10);print()
# Find the index with the maximum value in one of the arrays you've created
print(arr9.argmax());print()
# Sort the indexes of one of the arrays you just created
arr10.sort(0)
print(arr10);print()
arr10.sort(1)
print(arr10);print()

[[7 3 1]
 [5 5 9]
 [3 5 1]]

[[9 1 9]
 [3 7 6]
 [8 7 4]]

[[9 1 9]
 [3 7 6]
 [8 7 4]]
[[False  True False]
 [ True False  True]
 [False False False]]

[[ True False  True]
 [False  True False]
 [ True  True  True]]

[[False  True False]
 [ True False  True]
 [False False False]]

[[1 9 9]
 [3 6 7]
 [4 7 8]]

5

[[1 6 7]
 [3 7 8]
 [4 9 9]]

[[1 6 7]
 [3 7 8]
 [4 9 9]]



In [10]:
# Create an array with 10 evenly spaced numbers between 1 and 100
x=np.arange(1,100,10)
print(x)



[ 1 11 21 31 41 51 61 71 81 91]


In [11]:
# Find the indexes with the maximum values down the verticial axis
print(arr9.argmax(0));print()
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
print(arr9.argmin(1))

[0 1 1]

[2 0 2]
